version: "3"

networks:
  postgres-network:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    restart: always
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass123
    networks:
      - postgres-network
    ports:
      - "5050:80"